name: Build Wheels

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install maturin cibuildwheel

      - name: Build wheels
        run: |
          if [ ${{ matrix.os }} == 'ubuntu-latest' ]; then
            cibuildwheel --output-dir wheelhouse
          fi
        env:
          CIBW_BUILD: "cp36-abi3-* cp37-abi3-* cp38-abi3-* cp39-abi3-* cp310-abi3-*"
