name: Build Wheels

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]
        os: [ubuntu-latest, windows-latest]
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install maturin cibuildwheel

      - name: Build wheels
        run: |
          cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "cp38-abi3-* cp39-abi3-* cp310-abi3-*"
